### ISSUE TITLE
Create API gateway project with

### ISSUE THREAD

**Issue by Atloas** [Polsoftex-sp-z-o-o/ZdroweJedzenie-APIGateway#3]
1. basic login method using spring security + json web token with CUSTOMER and STAFF roles
2. login method uses credentials from UsersCredentialsProvider interface with a mock implementation
3. example hello world methods available to: everyone, customer,staff and both customer and staff

useful tutorial: https://blog.softtek.com/en/token-based-api-authentication-with-spring-and-jwt

**Comment by EasyL0ver** [comment]
project created
